'use client';

import React, { useState, useEffect, useRef } from 'react';
import { Save, Plus, Trash2, Code, Eye, Info, Sparkles } from 'lucide-react';
import styles from './templates.module.css';

const PLACEHOLDERS = [
  { label: 'Staff Name', value: '{{staff_name}}' },
  { label: 'Student Name', value: '{{student_name}}' },
  { label: 'Office City', value: '{{office_city}}' },
  { label: 'Meet Link', value: '{{google_meet_link}}' },
  { label: 'Event Date', value: '{{event_date}}' },
  { label: 'Current Date', value: '{{today}}' },
];

const DEFAULT_HTML = `<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: 'Inter', sans-serif; line-height: 1.6; color: #333; }
    .container { padding: 20px; border: 1px solid #eee; border-radius: 8px; }
    .header { color: #C9A227; font-size: 24px; margin-bottom: 20px; font-weight: bold; }
    .footer { margin-top: 30px; font-size: 12px; color: #888; border-top: 1px solid #eee; padding-top: 10px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">GT Group Official Notification</div>
    <p>Dear {{staff_name}},</p>
    <p>This is a test notification for the internal CRM system.</p>
    <div class="footer">
      Generated by GT Group CRM System
    </div>
  </div>
</body>
</html>`;

export default function EmailTemplateEditor() {
  const [templates, setTemplates] = useState([]);
  const [activeTemplate, setActiveTemplate] = useState(null);
  const [loading, setLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const textareaRef = useRef(null);

  useEffect(() => {
    fetchTemplates();
  }, []);

  const fetchTemplates = async () => {
    try {
      const res = await fetch('/api/admin/email-templates');
      const data = await res.json();
      setTemplates(data || []);
      if (data?.length > 0 && !activeTemplate) {
        setActiveTemplate(data[0]);
      }
    } catch (err) {
      console.error('Failed to fetch templates:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleSave = async () => {
    if (!activeTemplate) return;
    setIsSaving(true);
    try {
      const res = await fetch('/api/admin/email-templates', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(activeTemplate),
      });
      const data = await res.json();
      
      setTemplates(prev => {
        const index = prev.findIndex(t => t.id === data.id);
        if (index > -1) {
          const newArr = [...prev];
          newArr[index] = data;
          return newArr;
        }
        return [...prev, data];
      });
      setActiveTemplate(data);
      alert('Template saved successfully! ✅');
    } catch (err) {
      alert('Failed to save template. ❌');
    } finally {
      setIsSaving(false);
    }
  };

  const createNew = () => {
    const newTemplate = {
      template_name: 'New Template',
      subject: 'New Subject',
      body_html: DEFAULT_HTML,
      preview_text: 'Preview text for inbox...',
      placeholders: PLACEHOLDERS.map(p => p.value)
    };
    setActiveTemplate(newTemplate);
  };

  const insertPlaceholder = (val) => {
    if (!textareaRef.current) return;
    const textarea = textareaRef.current;
    const start = textarea.selectionStart;
    const end = textarea.selectionEnd;
    const text = activeTemplate.body_html;
    const before = text.substring(0, start);
    const after = text.substring(end, text.length);
    
    setActiveTemplate({
      ...activeTemplate,
      body_html: before + val + after
    });
    
    // Focus back on textarea after state update
    setTimeout(() => {
      textarea.focus();
      textarea.setSelectionRange(start + val.length, start + val.length);
    }, 0);
  };

  if (loading) return <div className={styles.emptyState}>Loading Editor...</div>;

  return (
    <div className={styles.container}>
      {/* Header */}
      <div className={styles.header}>
        <div className={styles.headerTitle}>
          <h1>Email Template Editor</h1>
          <p>Design and preview official GT Group communications</p>
        </div>
        <div style={{ display: 'flex', gap: '1rem' }}>
          <button className={styles.btnPrimary} onClick={createNew} style={{ background: 'var(--color-surface)', color: 'var(--color-text)', border: '1px solid rgba(255,255,255,0.1)' }}>
            <Plus size={18} /> New
          </button>
          <button className={styles.btnPrimary} onClick={handleSave} disabled={isSaving}>
            <Save size={18} /> {isSaving ? 'Saving...' : 'Save Template'}
          </button>
        </div>
      </div>

      <div className={styles.mainLayout}>
        {/* Sidebar */}
        <div className={styles.sidebar}>
          <div style={{ padding: '0.5rem', marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--color-gold)' }}>
            <Info size={16} /> <span>TEMPLATES</span>
          </div>
          {templates.map((t) => (
            <div 
              key={t.id} 
              className={`${styles.templateItem} ${activeTemplate?.id === t.id ? styles.active : ''}`}
              onClick={() => setActiveTemplate(t)}
            >
              <h5>{t.template_name}</h5>
              <small>{t.subject.substring(0, 30)}...</small>
            </div>
          ))}
        </div>

        {/* Editor Area */}
        {activeTemplate ? (
          <div className={styles.editorArea}>
            <div className={styles.formGrid}>
              <div className={styles.inputGroup}>
                <label>Template Name</label>
                <input 
                  value={activeTemplate.template_name} 
                  onChange={(e) => setActiveTemplate({...activeTemplate, template_name: e.target.value})}
                  placeholder="e.g., Staff Welcome"
                />
              </div>
              <div className={styles.inputGroup}>
                <label>Email Subject</label>
                <input 
                  value={activeTemplate.subject} 
                  onChange={(e) => setActiveTemplate({...activeTemplate, subject: e.target.value})}
                  placeholder="e.g., Welcome to GT Group 🇰🇷"
                />
              </div>
            </div>

            <div className={styles.editorGrid}>
              {/* Code Pane */}
              <div className={styles.codeBox}>
                <div className={styles.boxHeader}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <Code size={16} color="var(--color-gold)" />
                    <span>HTML Source</span>
                  </div>
                </div>
                <div className={styles.placeholderChips}>
                  {PLACEHOLDERS.map(p => (
                    <button key={p.value} className={styles.chip} onClick={() => insertPlaceholder(p.value)}>
                      {p.label}
                    </button>
                  ))}
                </div>
                <textarea 
                  ref={textareaRef}
                  className={styles.textarea}
                  value={activeTemplate.body_html}
                  onChange={(e) => setActiveTemplate({...activeTemplate, body_html: e.target.value})}
                />
              </div>

              {/* Preview Pane */}
              <div className={styles.previewBox}>
                <div className={styles.boxHeader}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <Eye size={16} color="var(--color-gold)" />
                    <span>Live Preview</span>
                  </div>
                  <small style={{ color: 'rgba(232, 232, 232, 0.4)' }}>Renders in real-time</small>
                </div>
                <div className={styles.previewFrame}>
                  <iframe 
                    title="Live Preview"
                    srcDoc={activeTemplate.body_html}
                    style={{ width: '100%', height: '100%', border: 'none' }}
                  />
                </div>
              </div>
            </div>
          </div>
        ) : (
          <div className={styles.emptyState}>
            <Sparkles size={48} />
            <p>Select or create a template to begin editing</p>
          </div>
        )}
      </div>
    </div>
  );
}
